PAPER:
  BaseItem_PAPER: 0
  desk_side_gaming: 1
  desk_mid_gaming: 2
  desk_gaming: 3
  desk_side_stylish: 4
  desk_mid_stylish: 5
  desk_stylish: 6
  desk_side_classic: 7
  desk_mid_classic: 8
  desk_classic: 9
  desk_side_cute: 10
  desk_mid_cute: 11
  desk_cute: 12
  chair_gaming: 13
  chair_stylish: 14
  chair_classic: 15
  chair_cute: 16
  laptop_gaming: 17
  laptop_macbook: 18
  laptop_office: 19
  vending_machine: 20
  book: 21
  book_office: 22
  pc_device_gaming: 23
  pc_gaming: 24
  digital_clock_gaming: 25
  digital_clock_stylish: 26
  microwave_normal: 27
  friedge_normal: 28
  book_office: 29
  tansu: 30
  table: 31
  shelf: 32
  register: 33
  doll_fox: 34
  prius_display: 35
  beer_mug: 36
  beer_mug_empty: 37
  beer_barrel: 38
  doll_fox_snow: 39
  slot: 40
  ishidouro: 41
  karesannsui_curve_l: 42
  karesannsui_curve_r: 43
  karesannsui_line: 44
  shishiodoshi: 45
  chair_houston: 46
  coffee_cup_houston: 47
  coffee_machine_houston: 48
  empty_cup_houston: 49
  gold_bar_houston: 50
  table_houston: 51
  chair_sofa_houston: 52
  tv_tvstand_corner_edition_houston: 53

LEATHER:
  BaseItem_LEATHER: 0
  prius: 1
  kart: 2
  timemachine: 3
  ebv_gg: 4
  ebv_gy: 5
  ebv_wlb: 6
  ebv_wp: 7

CLAY_BALL:
  BaseItem_CLAY_BALL: 0
  analog_clock_office: 1
  tv_stylish: 2
  outdoor_unit: 3
  aircon: 4
  postermagic: 5